# A friendly name for the workflow, which will be displayed in the GitHub Actions tab.
name: Daily Commit

# This section defines the triggers that will run the workflow.
on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

# VITAL: This block grants the necessary permissions for the GITHUB_TOKEN.
# The 'git push' command will fail without 'contents: write'.
permissions:
  contents: write

# A workflow run is made up of one or more jobs.
jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: THIS IS THE REQUIRED STEP THAT WAS MISSING.
      # It includes the specified email in its 'name'.
      - name: Step with email 24f3004403@ds.study.iitm.ac.in
        run: echo "This step is included to meet the task requirements."

      # Step 3: Create a commit
      - name: Create a new commit
        run: |
          # Configure git with a bot user name and email for attribution.
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Create or update a file to have something to commit.
          date >> daily-log.txt
          
          # Stage the new changes.
          git add daily-log.txt
          
          # Commit the changes with a standard message.
          git commit -m "Automated daily commit"
          
          # Push the changes back to the main branch of the repository.
          git push
